version: '2'
services:
  hive-metastore:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ytqiu/hive-metastore
    #external_links:
    #- hadoop
    #- zookeeper
    #- postgres
    networks:
      parrot:
        aliases:
        - hive-metastore
    volumes:
    - ./etc/supervisord.conf:/etc/supervisord.conf
    - ./etc/hive/conf/hive-site.xml:/etc/hive/conf/hive-site.xml
    environment:
      DB_TYPE: mysql 
    ports:
    - 9083:9083
  hive-metastore1:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ytqiu/hive-metastore
    #external_links:
    #- hadoop
    #- zookeeper
    #- postgres
    networks:
      parrot:
        aliases:
        - hive-metastore1
    volumes:
    - ./etc/supervisord.conf:/etc/supervisord.conf
    - ./etc/hive/conf/hive-site.xml:/etc/hive/conf/hive-site.xml
    environment:
      DB_TYPE: mysql 
    ports:
    - 9084:9083
networks:
  parrot:
    external:
      name: parrot
#  parrot:
#    driver: bridge
